name:                trench
version:             0.1.0.0
github:              "fabricatedmath/trench"
license:             BSD3
author:              "Charles Durham"
maintainer:          "fabricatedmath@gmail.com"
copyright:           "2018 Charles Durham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fabricatedmath/trench#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- linear
- repa
- mtl
- vector

library:
  source-dirs: src
  ghc-options:
    - -O2

executables:
  trench-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - trench
    - repa-io

tests:
  trench-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trench
